install: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y expect 
  - npm install coffee-script
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"

script: ./test/commands
